import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Stairs from "@/components/Stairs";


const jetBrainsMono = localFont({
  src: "./fonts/JetBrainsMono.woff2",
  variable: "--font-jet-brains-mono",
  weight: "100 200 300 400 500 600 700 800 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <Stairs/>
      </body>
    </html>
  );
}
